<a href="https://colab.research.google.com/github/MeFabiLuz/Marketing_Analitics/blob/main/Predicting_Customer_Churn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#1.Importando as bibliotecas

In [34]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import linear_model
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.model_selection import train_test_split

#2.Importando o dataset e medidas iniciais

In [35]:
data = pd.read_csv('/content/Shill_Bidding_Dataset.csv')

In [36]:
data.head()

,Record_ID,Auction_ID,Bidder_ID,Bidder_Tendency,Bidding_Ratio,Successive_Outbidding,Last_Bidding,Auction_Bids,Starting_Price_Average,Early_Bidding,Winning_Ratio,Auction_Duration,Class
0,1,732,_***i,0.200000,0.400000,0.0,0.000028,0.0,0.993593,0.000028,0.666667,5,0
1,2,732,g***r,0.024390,0.200000,0.0,0.013123,0.0,0.993593,0.013123,0.944444,5,0
2,3,732,t***p,0.142857,0.200000,0.0,0.003042,0.0,0.993593,0.003042,1.000000,5,0
3,4,732,7***n,0.100000,0.200000,0.0,0.097477,0.0,0.993593,0.097477,1.000000,5,0
4,5,900,z***z,0.051282,0.222222,0.0,0.001318,0.0,0.000000,0.001242,0.500000,7,0

In [37]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6321 entries, 0 to 6320
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Record_ID               6321 non-null   int64
 1   Auction_ID              6321 non-null   int64
 2   Bidder_ID               6321 non-null   object
 3   Bidder_Tendency         6321 non-null   float64
 4   Bidding_Ratio           6321 non-null   float64
 5   Successive_Outbidding   6321 non-null   float64
 6   Last_Bidding            6321 non-null   float64
 7   Auction_Bids            6321 non-null   float64
 8   Starting_Price_Average  6321 non-null   float64
 9   Early_Bidding           6321 non-null   float64
 10  Winning_Ratio           6321 non-null   float64
 11  Auction_Duration        6321 non-null   int64
 12  Class                   6321 non-null   int64
dtypes: float64(8), int64(4), object(1)
memory usage: 642.1+ KB

In [38]:
data.describe()

,Record_ID,Auction_ID,Bidder_Tendency,Bidding_Ratio,Successive_Outbidding,Last_Bidding,Auction_Bids,Starting_Price_Average,Early_Bidding,Winning_Ratio,Auction_Duration,Class
count,6321.000000,6321.000000,6321.000000,6321.000000,6321.000000,6321.000000,6321.000000,6321.000000,6321.000000,6321.000000,6321.000000,6321.000000
mean,7535.829457,1241.388230,0.142541,0.127670,0.103781,0.463119,0.231606,0.472821,0.430683,0.367731,4.615093,0.106787
std,4364.759137,735.770789,0.197084,0.131530,0.279698,0.380097,0.255252,0.489912,0.380785,0.436573,2.466629,0.308867
min,1.000000,5.000000,0.000000,0.011765,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000
25%,3778.000000,589.000000,0.027027,0.043478,0.000000,0.047928,0.000000,0.000000,0.026620,0.000000,3.000000,0.000000
50%,7591.000000,1246.000000,0.062500,0.083333,0.000000,0.440937,0.142857,0.000000,0.360104,0.000000,5.000000,0.000000
75%,11277.000000,1867.000000,0.166667,0.166667,0.000000,0.860363,0.454545,0.993593,0.826761,0.851852,7.000000,0.000000
max,15144.000000,2538.000000,1.000000,1.000000,1.000000,0.999900,0.788235,0.999935,0.999900,1.000000,10.000000,1.000000

#3.Tratamento dos dados

In [39]:
# remove the columns that are irrelevant to the case study

data.drop(["Record_ID","Auction_ID","Bidder_ID"],axis=1,\
inplace=True)

In [40]:
data.head()

,Bidder_Tendency,Bidding_Ratio,Successive_Outbidding,Last_Bidding,Auction_Bids,Starting_Price_Average,Early_Bidding,Winning_Ratio,Auction_Duration,Class
0,0.200000,0.400000,0.0,0.000028,0.0,0.993593,0.000028,0.666667,5,0
1,0.024390,0.200000,0.0,0.013123,0.0,0.993593,0.013123,0.944444,5,0
2,0.142857,0.200000,0.0,0.003042,0.0,0.993593,0.003042,1.000000,5,0
3,0.100000,0.200000,0.0,0.097477,0.0,0.993593,0.097477,1.000000,5,0
4,0.051282,0.222222,0.0,0.001318,0.0,0.000000,0.001242,0.500000,7,0

#4.Desenvolvendo o modelo

In [41]:
X = data.drop("Class",axis=1)
y = data["Class"]

# Split the dataset into training and testing sets

X_train,X_test,y_train,y_test = train_test_split\
(X,y,test_size=0.3,\
random_state=1, stratify=y)

In [42]:
# Print the size of training and testing datasets

print("Training dataset size: {}, Testing dataset size: {}"\
.format(X_train.shape,X_test.shape))

Training dataset size: (4424, 9), Testing dataset size: (1897, 9)

In [43]:
# Fit the model using linear regression

linear = linear_model.LinearRegression()
linear.fit(X_train,y_train)

LinearRegression()

In [44]:
# Predict on the first 10 test data points using the following code

linear.predict(X_test)[:10]

array([-0.00375542, -0.00248633, -0.01090699, -0.02753235,  0.01939224,
        0.99493654,  0.02761226, -0.00565047,  0.48101551,  0.00471959])

In [45]:
# Now check the actual target values using y_test[:10].values:
y_test[:10].values

array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0])

In [46]:
# Evaluate the score of the linear regression model on the training and testing datasets:

print("Score on training dataset: {}, "\
"Score on testing dataset: {}"\
.format(linear.score(X_train,y_train),\
linear.score(X_test,y_test)))

Score on training dataset: 0.8166836356918417, Score on testing dataset: 0.8119909602893054

In [47]:
# Fit the model using logistic regression as follows

logit = linear_model.LogisticRegression()
logit.fit(X_train,y_train)

LogisticRegression()

In [49]:
# Predict on the test data:

logit.predict(X_test)[:10]

array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0])

In [50]:
# Check the actual target values with y_test[:10].values:

y_test[:10].values

array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0])

In [51]:
# Similar to linear regression, find the score on the training and testing datasets as follows:

print("Score on training dataset: {}, "\
"Score on testing dataset: {}"\
.format(logit.score(X_train,y_train),\
logit.score(X_test,y_test)))

Score on training dataset: 0.9794303797468354, Score on testing dataset: 0.9715340010542962